# Docker-compose version
version: '3'

# Define the services/containers to be run
services:
      
  # Database
  database:
    # image to build container from
    image: postgres:11-alpine 
    ports:
      - "27018:27017"
    networks:
      - backend_network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
       - ./server/script/schemaDb_demo_db_postgresql.sql:/docker-entrypoint-initdb.d/schemaDb_demo_db_postgresql.sql
       
  # Backend
  backend: 
    # directory of Dockerfile
    build: ./server
    ports:
      - "3000:3000"
    # link this service to database service
    links:
      - database 
    environment:
      - DB_HOST=database
    networks:
      - backend_network
    depends_on:
      - database
      
  # Frontend
  frontend:
    build: ./client
    ports:
      - "2000:2000"
    networks:
      - frontend_network

  # Proxy server
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
  backend_network: